---
- name: Prepare
  hosts: servers
  gather_facts: no
  tasks:
    - name: Install systemd
      dnf:
        name: systemd
        state: latest

    - name: Install Python3
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - python3
        - python3-pip
        - python3-setuptools

    - name: Install dnspython (required for nsupdate and dig)
      command:
        cmd: pip3 install dnspython
      changed_when: false