---
- name: Prepare
  hosts: servers
  gather_facts: no
  tasks:
    - name: Install systemd
      dnf:
        name: systemd
        state: latest
#      when:
#        - type == "master" or type == "slave"

    - name: Install Python3 via PIP
      dnf:
        name: python3-pip
        state: latest

    - name: Install setuptools and dnspython
#      command:
#        cmd: "pip3 install setuptools"
      pip:
        name:
          - setuptools
          - dnspython

#    - name: Install dnspython
#      command:
#        cmd: "pip3 install dnspython"