---
- name: Check only on master
  block:
    - name: Check certificate is available
      stat:
        path: "/etc/ssl/cert/{{ common_name }}.crt"
      register: certfile_stat

    - name: Check certificate dates
      command:
        cmd: "openssl x509 -in /etc/ssl/cert/{{ common_name }}.crt -noout -startdate -enddate"
      register: certificate_enddate
      when:
        - certfile_stat.stat.exists
        - certfile_stat.stat.isreg

    - name: Print certificate start and end dates
      debug:
        var: certificate_enddate.stdout_lines
      when:
        - certfile_stat.stat.exists
        - certfile_stat.stat.isreg
        - certificate_enddate is defined

    # https://stackoverflow.com/questions/44546154/jmespathtypeerror-when-using-json-query-filter-in-ansible-with-starts-with
    - name: Extract start and end dates
      set_fact:
        start_date: "{{ certificate_enddate.stdout_lines | to_json | from_json | json_query(START_DATE_QUERY) | join() | regex_replace('notBefore=(?P<startDate>.*)', '\\g<startDate>') }}"
        end_date: "{{ certificate_enddate.stdout_lines | to_json | from_json | json_query(END_DATE_QUERY) | join() | regex_replace('notAfter=(?P<endDate>.*)', '\\g<endDate>') }}"
      vars:
        START_DATE_QUERY: "[?contains(@, 'notBefore') == `true`]"
        END_DATE_QUERY: "[?contains(@, 'notAfter') == `true`]"
      when:
        - certfile_stat.stat.exists
        - certfile_stat.stat.isreg
        - certificate_enddate is defined
        - certificate_enddate.stdout_lines | type_debug == "list"

    - name: Print certificate start and end dates
      debug:
        msg: "Certificate start date: {{ start_date }} and end date: {{ end_date }}"

    - name: Get server date time
      shell:
        cmd: 'TZ=GMT date +"%Y-%m-%d %H:%M:%S"'
      register: server_date_time

    - name: Print server date time
      debug:
        msg: "Server current date time: {{ server_date_time.stdout }} GMT."

    - name: Print if certificate is still valid
      debug:
        msg: "Certificate is still valid."
      when:
        - (server_date_time.stdout | to_datetime) >= (start_date | to_datetime('%b %d %H:%M:%S %Y %Z'))
        - (server_date_time.stdout | to_datetime) <= (end_date | to_datetime('%b %d %H:%M:%S %Y %Z'))

    - name: Print if certificate is not valid
      debug:
        msg: "Certificate is not valid."
      when: >
        ((server_date_time.stdout | to_datetime) < (start_date | to_datetime('%b %d %H:%M:%S %Y %Z'))) or
        ((server_date_time.stdout | to_datetime) > (end_date | to_datetime('%b %d %H:%M:%S %Y %Z')))
  when:
    - type is defined
    - type == "master"
...