# This is a basic workflow that is manually triggered

name: Run Ansible Molecule tests
on: [workflow_dispatch]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:    
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Test Ansible roles with Molecule
        uses: ./.github/actions/molecule-test
